Repository today-they-learned/ttl_api, pull requests merged in 2022-02, with the labels that each got.

#35 기본적인 drf 활용한 Article API
  article/migrations/0002_auto_20220130_2150.py
  article/permissions.py
  article/serializers/__init__.py
  article/serializers/article_serializer.py
  article/urls.py
  article/views.py
  article/views/__init__.py
  article/views/article_list_create_api_view.py
  article/views/article_retrieve_update_destroy_api_view.py
  config/settings.py
  config/urls.py
  requirements.txt
Labels: API 제작

#40 feat: study model
  config/settings.py
  study/__init__.py
  study/admin.py
  study/apps.py
  study/migrations/0001_initial.py
  study/migrations/__init__.py
  study/models/__init__.py
  study/models/study.py
  study/tests.py
Labels: 모델 구성

#42 root url에서 404 대신 swagger 화면이 뜨도록 함.
  config/urls.py
Labels: documentation, enhancement

#43 grass, bookmark 모델 생성
  article/admin.py
  article/migrations/0003_bookmark.py
  article/models/__init__.py
  article/models/bookmark.py
  user/admin/__init__.py
  user/admin/grass.py
  user/migrations/0008_grass.py
  user/models/__init__.py
  user/models/grass.py
Labels: 모델 구성

#44 Bookmark api
  article/models/bookmark.py
  article/serializers/__init__.py
  article/serializers/bookmark_serializer.py
  article/urls.py
  article/views/__init__.py
  article/views/bookmark_create_api_view.py
  article/views/bookmark_destroy_api_view.py
  user/models/grass.py
Labels: API 제작

#56 Feedback model,admin
  article/admin/__init__.py
  article/admin/feedback.py
  article/models/__init__.py
  article/models/feedback.py
Labels: 모델 구성

#61 article 검색 api
  article/views/article_list_create_api_view.py
Labels: API 제작

#62 Follow api
  .idea/ttl_api.iml
  article/views/article_list_create_api_view.py
  article/views/article_retrieve_update_destroy_api_view.py
  comment/views/comment_create_api_view.py
  comment/views/comment_retrieve_update_destroy_api_view.py
  user/serializers/__init__.py
  user/serializers/follow_serializer.py
  user/urls.py
  user/views/__init__.py
  user/views/follow_create_api_view.py
  user/views/follow_destroy_api_view.py
  user/views/follow_list_api_view.py
Labels: API 제작

#64 django-taggit-serializer가 제대로 동작하지 않아 custom / article에 tags 추가
  article/filters/__init__.py
  article/filters/tags_filter.py
  article/migrations/0006_auto_20220209_2101.py
  article/models/article.py
  article/serializers/article_serializer.py
  article/views/article_list_create_api_view.py
  tag/serializers.py
  user/serializers/user_serializer.py
Labels: 모델 구성, API 제작

#73 feat: background task를 통해 깃헙 TIL 가져오는 기능 추가
  article/tasks/__init__.py
  article/tasks/collect_github_til_task.py
  config/settings.py
  config/urls.py
  requirements.txt
  user/apps.py
  user/models/user.py
  user/serializers/user_serializer.py
  user/signals.py
  utils/analyze_github_til.py
Labels: enhancement, API 제작

#75 feat: image uploader
  article/migrations/0013_uploadimage.py
  article/models/__init__.py
  article/models/upload_image.py
  article/serializers/__init__.py
  article/serializers/bookmark_serializer.py
  article/serializers/upload_image_serializer.py
  article/urls.py
  article/views/__init__.py
  article/views/article_list_create_api_view.py
  article/views/upload_image_create_api_view.py
  user/serializers/follow_serializer.py
Labels: API 제작

#85 github collector의 생성/수정 일자를 Grass 모델에 반영시키기
  Dockerfile
  article/tasks/collect_github_til_task.py
  user/migrations/0012_auto_20220214_2127.py
  user/models/grass.py
  utils/analyze_github_til.py
Labels: enhancement

#86 velog collector의 생성 일자를 Grass 모델에 반영시키기
  article/tasks/collect_velog_til_task.py
Labels: enhancement

#90 user 모델에 avatar Image 필드 추가
  user/migrations/0013_user_avatar.py
  user/models/user.py
  user/serializers/user_serializer.py
Labels: API 제작

#91 정기 스케쥴러 추가
  article/tasks/refresh_user_collect_github.py
  article/tasks/refresh_user_collect_velog.py
  config/celery.py
Labels: enhancement
